#!/usr/bin/env bash

# wget https://github.com/libgit2/libgit2/archive/v0.24.2.tar.gz
# tar xzf v0.24.2.tar.gz
# cd libgit2-0.24.2/
# cmake .
# make

mkdir libgit2
cd libgit2
git init
git remote add origin https://github.com/libgit2/libgit2.git
git pull origin v0.24.3
mkdir build
cd build
cmake ..
