#!/usr/bin/env bash

BIN_INSTALL_DIR="`pwd`/git2/bin"
LIB_INSTALL_DIR="`pwd`/git2/lib"
INCLUDE_INSTALL_DIR="`pwd`/git2/include"
BUILD_CLAR=off
mkdir -p "${BIN_INSTALL_DIR}"
mkdir -p "${LIB_INSTALL_DIR}"
mkdir -p "${INCLUDE_INSTALL_DIR}"
mkdir libgit2
cd libgit2
git init
git remote add origin https://github.com/libgit2/libgit2.git
git pull origin v0.24.3
mkdir build
cd build
cmake \
  -DBIN_INSTALL_DIR="${BIN_INSTALL_DIR}" \
  -DLIB_INSTALL_DIR="${LIB_INSTALL_DIR}" \
  -DINCLUDE_INSTALL_DIR="${INCLUDE_INSTALL_DIR}" \
  -DBUILD_CLAR="${BUILD_CLAR}"
  ..
cmake --build . --target install
cd ../..
export CRYSTAL_GIT_LDFLAGS="-L`pwd`/git2/lib"
crystal spec -D travis
