#!/usr/bin/env bash

echo cd `pwd`
mkdir libgit2
cd libgit2
git init
git remote add origin https://github.com/libgit2/libgit2.git
git pull origin v0.24.3
mkdir build
cd build
cmake ..
cmake --build .
ls -all
cd ../..
echo cd `pwd`
export CRYSTAL_GIT_LDFLAGS="-L`pwd`/libgit2/build"
crystal spec -D travis
